---
es:
  uri: http://elasticsearch-master.elastic.svc.cluster.local:9200/
  snapshots: false

serviceMonitor:
  ## Need to create a serviceMonitor so this exporter can been seen by prom
  ## Labels need to match the names of the prom esp. release.
  ## To check if its working you can check the Prom targets at
  ## http://localhost:9090/targets
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true
  namespace: kube-system
  labels:
    prometheus: prometheus-stack-kube-prom-prometheus
    release: prometheus-stack
  interval: 10s
  scrapeTimeout: 10s
  scheme: http
  relabelings: []
  targetLabels: []
  metricRelabelings: []
  sampleLimit: 0
