---
docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint | tee /tmp/lint.log
  dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet-4-151612
    steps:
      - checkout
      - run: activate-gcloud-account.sh
      - run: make dev | tee /tmp/deploy.log
  prod:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - checkout
      - run: activate-gcloud-account.sh
      - run: make prod | tee /tmp/deploy.log
workflows:
  version: 2
  commit:
    jobs:
      - lint:
          context: org-global
      - dev:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - develop
      - prod:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - main
